apiVersion: v1
kind: Secret
metadata:
  name: abonnement-secrets
type: Opaque
stringData:
  STRIPE_SECRET_KEY: "sk_test_<your_stripe_key>"
  STRIPE_WEBHOOK_SECRET: "whsec_<your_stripe_webhook_secret>"
  PAYPAL_CLIENT_ID: "<your_paypal_client_id>"
  PAYPAL_CLIENT_SECRET: "<your_paypal_client_secret>"
  PAYPAL_WEBHOOK_ID: "<your_paypal_webhook_id>"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "secret"
  MYSQL_USERNAME: "abonnement_user"
  MYSQL_PASSWORD: "Atest4prctise"
