apiVersion: v1
kind: Service
metadata:
  name: abonnement
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  selector:
    app: abonnement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
